### ISSUE TITLE
Enable loading of completed tasks in "Completed" view

### ISSUE THREAD

**Issue by Gerii** [owncloud/tasks#340] opened 2016-07-28 18:37 UTC
### Steps to reproduce
1. Set Completed list to visible and open it
### Expected behaviour

All completed tasks should be shown
### Actual behaviour

None are shown

All completed tasks are only shown in the Completed list when "Load remaining completed tasks" has been clicked in each of the individual task lists.

**Tasks version:** (see ownCloud apps page)
0.9.2

**Comment by raimund-schluessler** [comment] 2016-07-28 18:42
This is the intended behaviour. If we load all completed tasks the app will become terribly slow (at least if you have very much of them, which happens easily if you use owncloud a lot).

Sadly there is no possibility to e.g. load only the five recently completed tasks for each calendar. So the only way is to not load these tasks at all when the app is loaded.

However, one could think about if it makes sense to load the completed tasks when the Completed list is openend. But again, this will slow down the app significantly (you can try by loading all completed tasks for all calendar.s).

**Comment by Gerii** [comment] 2016-07-28 18:49
Didn't think about that, but it does look like a bug if I have completed tasks but none are showing up in the completed list.
As I started using ownCloud a few months ago I only have 6 calendars with maybe 50 completed tasks, so it's not that slow I guess. Maybe you could add a button like in the individual calendars? Something like "Load remaining completed tasks from all lists (slow)". Or if that's not feasible at least a disclaimer that only completed tasks that have been loaded individually show up here.

**Comment by raimund-schluessler** [comment] 2016-07-28 20:33
Yes, that sounds like a good idea. I changed the title accordingly.

**Comment by lizeidsness** [comment] 2017-05-02 20:32
my 2 cents - at the moment it's not possible to find a task that has been marked complete if the task was checked in a remote client, so that's more than a mere enhancement.

Also - saying there are too many records, isn't a good reason, when email inboxes load commonly with thousands of records.  If necessary, page the list as suggested above, with a "load more records" button/option like many do.

**Closed** 2017-12-20 15:35 UTC
Labels: enhancement
