### ISSUE TITLE
Crash on owncloud 9.0RC3

### ISSUE THREAD

**Issue by Xefir** [owncloud/tasks#295] opened 2016-03-08 09:07 UTC
### Steps to reproduce
1. Install owncloud 9.0RC3
2. Install Task app on DAVClient branch
3. Go to /index.php/apps/tasks/

### Expected behaviour
Display the Tasks page

### Actual behaviour
It crash (500 Internal Server Error)

### Server configuration
**Operating system**: `Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u3 (2016-01-17) x86_64 GNU/Linux`

**Web server:** `nginx version: nginx/1.6.2`

**Database:** `mysql  Ver 15.1 Distrib 10.0.23-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2`

**PHP version:** `PHP 5.6.17-0+deb8u1 (cli) (built: Jan 13 2016 09:10:12)`

**ownCloud version:** (see ownCloud admin page) `9.0RC3`

**Updated from an older ownCloud or fresh install:** `Upgraded from 9.0RC1`

**Where did you install ownCloud from:** `git clone`

**List of activated apps:**

```
Enabled:
  - activity: 2.2.1
  - calendar: 1.0
  - comments: 0.2
  - contacts: 1.0.0.0
  - dav: 0.1.5
  - direct_menu: 0.6
  - documents: 0.12.0
  - encryption: 1.2.0
  - external: 1.2
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_clipboard: 0.4.2
  - files_external: 0.5.2
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - mail: 0.3.0
  - music: 0.3.9
  - news: 7.1.2
  - notes: 2.0.0
  - notifications: 0.2.3
  - ocsms: 1.6.0
  - passman: 1.3.38
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - tasks: 0.9.0
  - templateeditor: 0.1
  - updatenotification: 0.1.0
  - user_external: 0.4
  - user_ldap: 0.8.0
Disabled:
  - registration
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "51654eb6095f6",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "9.0.0.18",
        "dbname": "cloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "appstoreenabled": false,
        "loglevel": 2,
        "theme": "",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "forcessl": true,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu"
    }
}
```

**Are you using external storage, if yes which one:** `no`

**Are you using encryption:** `no`

**Are you using an external user-backend, if yes which one:** `no`

### Client configuration
**Browser:** `Google Chrome Version 49.0.2623.75 (64-bit)`

**Operating system:** `Mac OSX 10.11.3 - Darwin 15.3.0 Darwin Kernel Version 15.3.0: Thu Dec 10 18:40:58 PST 2015; root:xnu-3248.30.4~1/RELEASE_X86_64 x86_64`

#### Web server error log
```
2016/03/08 10:04:03 [error] 10794#0: *61147 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Call to undefined function OCA\Tasks\Controller\script() in apps/tasks/controller/pagecontroller.php on line 60
PHP message: PHP Stack trace:
PHP message: PHP   1. {main}() index.php:0
PHP message: PHP   2. OC::handleRequest() index.php:39
PHP message: PHP   3. OC\Route\Router->match() lib/base.php:873
PHP message: PHP   4. call_user_func:{lib/private/route/router.php:273}() lib/private/route/router.php:273
PHP message: PHP   5. OC\AppFramework\routing\RouteActionHandler->__invoke() lib/private/route/router.php:273
PHP message: PHP   6. OC\AppFramework\App::main() lib/private/appframework/routing/routeactionhandler.php:45
PHP message: PHP   7. OC\AppFramework\Http\Dispatcher->dispatch() lib/private/appframework/app.php:110
PHP message: PHP   8. OC\AppFramework\Http\Dispatcher->executeController() lib/private/appframework/http/dispatcher.php:89
PHP message: PHP   9. call_user_func_array:{lib/private/appframework/http/dispatcher.php:159}() lib/private/appframework/http/dispatcher.php:159
PHP message: PHP  10. OCA\Tasks\Controller\PageController->index() lib/private/appframework/http/dispatcher.php:159" while reading response header from upstream, client: 127.0.0.1, server: nope, request: "GET /index.php/apps/tasks/ HTTP/1.1", upstream: "fastcgi://unix:/var/run/ajenti-v-php-fcgi-cloud-php-fcgi-0.sock:", host: "nope"
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"HGwcXc6AFuzKDH9t9sUo","remoteAddr":"127.0.0.1","app":"PHP","message":"Call to undefined function OCA\\Tasks\\Controller\\script() at apps\/tasks\/controller\/pagecontroller.php#60","level":3,"time":"2016-03-08T08:48:23+00:00"}
```

#### Browser log
```
Request URL:/index.php/apps/tasks/
Request Method:GET
Status Code:500 Internal Server Error
Remote Address:nope:443
Response Headers
cache-control:no-store, no-cache, must-revalidate, post-check=0, pre-check=0
content-security-policy:default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src * data: blob:; font-src 'self' data:; media-src *; connect-src *
content-type:text/html; charset=UTF-8
date:Tue, 08 Mar 2016 09:06:15 GMT
expires:Thu, 19 Nov 1981 08:52:00 GMT
pragma:no-cache
server:nginx
status:500 Internal Server Error
version:HTTP/1.1
```

**Comment by raimund-schluessler** [comment] 2016-03-08 09:34
Thanks for the report, however I can't reproduce this error on v9.0.0RC3. I guess, that something is wrong with your owncloud installation. The undefined function ```OCA\\Tasks\\Controller\\script()``` is an owncloud internal function which is still included in 9.0 and is advised to be used for including javascript: https://doc.owncloud.org/server/9.0/developer_manual/app/templates.html#including-css-and-javascript

Other apps do use it too, e.g. calendar. Does the calendar work for you?

**Comment by Xefir** [comment] 2016-03-08 21:10
Yes it works, I got only this app not working (and I have a lot running)

**Comment by raimund-schluessler** [comment] 2016-03-08 21:29
Sorry, I have no idea why it could not work. It is especially weird since the ```script()``` function is already used six times before line 60 of ```pagecontroller.php```.

**Comment by Henni** [comment] 2016-03-08 22:10
@raimund-schluessler I was able to reproduce this by disabling debugging in the config.php

**Comment by raimund-schluessler** [comment] 2016-03-08 22:24
Indeed, I also see this with Debug => false. Weird problem.

**Comment by Henni** [comment] 2016-03-08 22:36
Enabling debugging shouldn't modify behaviour. This is really strange...
Maybe try `\OCP\Util::addScript('myapp', 'script'); ` for now.

**Comment by raimund-schluessler** [comment] 2016-03-08 22:40
I fixed the problem by removing the script calls from ```pagecontroller.php```and adding them to ```templates\main.php```. I have no idea why this helps or why it is necessary. Maybe we should report this in core?

**Comment by Henni** [comment] 2016-03-08 22:48
@raimund-schluessler really seems to be a core issue, as it depends on the debug config value.

**Comment by raimund-schluessler** [comment] 2016-03-09 09:17
The issue is fixed in the current DAVclient branch.

**Closed by raimund-schluessler** 2016-03-09 09:17 UTC

**Comment by Xefir** [comment] 2016-03-09 09:23
Can confirm. Thank you :)
