### ISSUE TITLE
Subtasks and Today / Week Overview

### ISSUE THREAD

**Issue by Remich** [owncloud/tasks#284] opened 2015-12-11 17:03 UTC
The subtasks are not displayed in the "Today" or "Week" categories.

Example: Parent task doesn't have a start and due date, but the subtask has. The subtask should be displayed in the "Today" / "Week" categories.

**Comment by raimund-schluessler** [comment] 2015-12-12 17:00
This currently is by design. If we want to show a subtask with a due date in the today/week view, we must do this by showing it with its parent/root task. Showing a subtask alone would be confusing as it then appears to be a root task.

On the other hand, I am not sure, if it is reasonable to show the root task there as it has no due date, bu only its subtask has. We need some more opinions here.

**Comment by TraceyC77** [comment] 2015-12-21 15:27
I'm looking at this to replace Toodledo for my task management. There are definitely use cases for having subtasks show up on different days. Here is one such use case.

- I have a long term project such as "organize the garage" which is due 2 months from now
- There are subtasks that may have different due dates such as "order shelves" and "install shelves"

It is ideal to show me the subtasks in the "Today" or "Week" categories so I can easily see which sub-task I need to do next

**Comment by raimund-schluessler** [comment] 2015-12-21 15:35
I agree with this use case, but the question is how to show these subtasks.

The point is that we cannot show them alone, because then the correlation to the parent task is lost, which leads to confusion. Hence we must also show the parent task. But then we also have to show all other subtasks of this parent task, as only showing the due subtask may confuse the user too. But then we end up showing a lot of tasks which are actually not due in the next time.

So what is your proposal for this dilemma?

**Comment by Remich** [comment] 2015-12-26 08:31
I don't think it would confuse the user when only the due subtask with their parent are displayed. I mean this is exactly what the overview for Today / Week etc.. is for. 
I think it would be more confusing to show all subtasks, even the ones which aren't due.

Maybe you can change the UI style a little, so that the subtasks have a different style. This way you can even show them without their parent.

The fact that subtasks are missing from the Today / Week overview is a huge flaw in my opinion. This issue made me switch to wunderlist.

**Comment by SteOtt** [comment] 2016-02-24 21:31
I would also like to see the subtasks with a due date in the day- and week-view.
My favourite solution would look like this:
- show all tasks with a due date in the day- and week-view no matter if it is a parent task, or a child task
- show all the parent tasks of the task with a due date (there might be more than one) to the root task
- don't show the sibling tasks of the task with a due date.

I miss this feature a lot.

**Comment by esaule** [comment] 2016-03-08 04:18
I miss this feature as well. In my opinion, if a task (sub task or whatever) should show up on the daily and weekly views. If it were me I would show the parent(s) task greyed-out to indicate more clearly that they are not the due one.

**Comment by qgp** [comment] 2016-06-22 11:44
I support that request, at the moment the fact that subtasks are not shown in the overview page renders them unusable for me. For me the point of subtasks is to break down larger ones and then you want to see the part that needs to be done today/this week. Not showing them at all although they are due is confusing, to say the least.

**Comment by ccoenen** [comment] 2016-09-25 08:34
@esaule this is also what FogBugz does in a similar scenario: I have a hierarchical list of issues (they call them cases). Some of those match my filter, some of those do not. The screenshot shows a Bug that has been assigned to me. But the Hierarchical structure above is _not_ assigned to me. I still get them for context, but they are greyed out.

![fogbugz-parent-cases](https://cloud.githubusercontent.com/assets/124909/18813930/7fe33d3e-830b-11e6-992a-59919ebdcabf.png)

With FogBugz I also get the "[1 subcase not matching search]" Link which lets me see sibling tasks that may be relevant.

**Closed** 2017-12-20 15:40 UTC
