### ISSUE TITLE
Completed count missing

### ISSUE THREAD

**Issue by kordianbruck** [owncloud/tasks#183] opened 2015-06-17 17:41 UTC
The complete category is missing the count of items. Maybe this is intended.

**Comment by raimund-schluessler** [comment] 2015-06-17 18:45
This is not a bug, but intended. For example I have several hundreds of completed tasks which means the number shown would get really big. This would look ugly and potentially break the layout. Also I don't see any benefit in knowing the exact count of your completed tasks.

**Comment by Henni** [comment] 2015-06-17 18:47
@raimund-schluessler maybe the large number problem could be solved by limiting it to a maximum of 999 as proposed by the [css documentation](https://doc.owncloud.org/server/8.0/developer_manual/app/css.html#menus)

**Comment by raimund-schluessler** [comment] 2015-06-17 18:50
Ah, alright, I wasn't aware of such a proposal. Thanks for the hint. Sounds like a usefull idea.

**Comment by raimund-schluessler** [comment] 2015-06-17 20:12
Fixed with https://github.com/owncloud/tasks/commit/c73ac27bc1d28dc3ad8682b28d9689f6a7057638

**Comment by Henni** [comment] 2015-06-17 20:20
This looks good but isn't perfect. The count only shows the number of currently listed tasks and doesn't count the hidden completed tasks.

**Comment by raimund-schluessler** [comment] 2015-06-17 20:46
Should be good with https://github.com/owncloud/tasks/commit/03308d884e6843c8e0240f69dfbefa1ec250cb81 now

**Comment by Henni** [comment] 2015-06-17 20:49
Awesome!

**Comment by raimund-schluessler** [comment] 2015-06-17 20:49
:)

**Comment by jancborchardt** [comment] 2015-06-19 14:16
I wouldn’t really show the completed count either. As @raimund-schluessler says it’s not really that interesting, and it’s just another number which takes away focus from the really important numbers. Just because we _can_ show it doesn’t mean we should.

There’s also not really an email app which permanently displays the number of emails in your trash. ;) So I’d say it should be removed again.

**Comment by raimund-schluessler** [comment] 2015-06-19 14:30
Well, then I will remove it again, but at least we now have a counter formatter for the other numbers (although I doubt that anybody has more than 999 open tasks, but you never know).

**Closed** 2015-06-19 18:22 UTC
Labels: enhancement

**Comment by jancborchardt** [comment] 2015-06-20 11:08
@raimund-schluessler thanks!
