### ISSUE TITLE
v0.9.1 Completed task not showing 

### ISSUE THREAD

**Issue by jedjann** [owncloud/tasks#327] opened 2016-07-19 05:36 UTC
completed task data does not appear. but when i complete a task it shows the data.
sometimes the Load remaining completed tasks doesn't appear

![complete task1](https://cloud.githubusercontent.com/assets/17632951/16939785/564a6f76-4db7-11e6-92b5-d431703aa722.jpg)
![complete task3](https://cloud.githubusercontent.com/assets/17632951/16939783/564a02c0-4db7-11e6-8dfc-777abecb63cd.jpg)
![complete task2](https://cloud.githubusercontent.com/assets/17632951/16939784/564a3ae2-4db7-11e6-85c3-54c0d2048bf3.jpg)

**Comment by raimund-schluessler** [comment] 2016-07-21 10:53
Thanks for the report. You are right, it behaves weird/wrong. I will try to summarize it and make clear how it should work and what is a bug.

- Completed tasks are not loaded: This is by design. Loading all completed tasks would make the app very slow and normally you don't need to see all the tasks you completed already. If you do, there should be the "Load remaining completed tasks" button.

- Load tasks button is not shown: This is a bug. This button should always be shown. However, if you hide the completed tasks, it will also hide the button. This was useful in the past when the five newest completed tasks where loaded on app start but it is bad now because you will only see the button after you have completed a task in the app. Issue for this bug: https://github.com/owncloud/tasks/issues/331

- Completed tasks not shown after loading them: This problem is really weird and I just noticed it when I tried to understand your problem. After the app start you click on the "Load... " button and the completed tasks are loaded and shown as they should. But if you completed a task after the app start, then only one completed task is shown after loading and also just after you clicked somewhere (triggered and AngularJS digest cycle). Issue for this weird thing: https://github.com/owncloud/tasks/issues/332

I will close this issue here and proceed with the two issues listed above.

**Closed by raimund-schluessler** 2016-07-21 10:53 UTC
