### ISSUE TITLE
Make the software ready for nextcloud

### ISSUE THREAD

**Issue by Liwindo** [owncloud/tasks#348] opened 2016-08-15 12:13 UTC
Is it possible that you open the software for nextcloud?

**Comment by dper** [comment] 2016-08-16 14:04
@Liwindo It already works on NextCloud.

**Comment by Liwindo** [comment] 2016-08-16 15:21
@dper No, it shows just the hint "ownCloud 9.1 or higher is required."

**Comment by dper** [comment] 2016-08-16 16:07
In fact many of us are already using Tasks with NextCloud. It works. :-)

Perhaps you found some out of date documentation?

**Comment by gpaumier** [comment] 2016-08-16 16:23
I think the problem @Liwindo encounters is that Tasks 0.9.3 [requires](https://github.com/owncloud/tasks/commit/d758d2637500405fa29af0cea1feccb648b7848a#diff-224bb875c5d3cfcd7621135069013242L13) version 9.1 or higher of *cloud. This works for the latest version of owncloud, but not for nextcloud since its latest version is 9.0.53. A workaround is to install Tasks 0.9.2 instead.

**Comment by raimund-schluessler** [comment] 2016-08-16 19:18
Or to manually change the required version to 9.0 and test if it works. Worst think that could happen is that it breaks the colorpicker function.

**Comment by Liwindo** [comment] 2016-08-16 23:07
Yeah, both solutions work. Nevertheless would be an official nextcloud support great, especially for the next versions.

**Comment by proninyaroslav** [comment] 2016-08-17 09:21
I have the same problem and workaround is change `min-version` in info.xml to 9.0.

**Comment by aktavor69** [comment] 2016-08-18 12:00
It's doesnt work for me. I made the change from 9.1 to 9.0 on info,xml but the app still not appear on disabled apps :/

There is something else to do ? 

Thanks

**Comment by Liwindo** [comment] 2016-08-18 12:17
Do you take tasks 9.3 for nextcloud 9.0.53?

**Comment by aktavor69** [comment] 2016-08-18 12:18
Its ok now, thanks. IDK why its not working but after 10min, the app appears 

Thanks for your help

**Comment by ezraholm50** [comment] 2016-08-20 12:20
Both solutions don't work on my server, tried to lower it to 9.0 and even 8. From the ownCloud apps website tried to download previous releases but still the same problem.

Also tried clearing cache from the browser, reloading apache2 etc...

**Comment by raimund-schluessler** [comment] 2016-08-22 13:29
As I see it, the problem is more "Make nextcloud ready for Tasks 0.9.3" instead of "Make Tasks ready for nextcloud". Hence, I am going to close this issue here. If someone confirms, that Tasks 0.9.3 works without problems with oC 9.0 I am willing to lower the require-min property to allow oC 9.0 and hence nextcloud < 10  for the next release.

**Closed by raimund-schluessler** 2016-08-22 13:29 UTC
