### ISSUE TITLE
Issue by installing on ownCloud 9.1.5

### ISSUE THREAD

**Issue by reaphil** [owncloud/tasks#385] opened 2017-05-18 16:28 UTC
After i try to activate the plugin i get the following message:

Tasks 0.9.4 
Client error response [url] https://apps.owncloud.com/CONTENT/content-files/174834-jj%3Cimg%20src= [status code] 404 [reason phrase] Not Found

**Comment by mach-o** [comment] 2017-05-22 15:59
Duplicate of #383

**Comment by jancborchardt** [comment] 2017-05-23 08:51
Closing as duplicate of #383, thanks @mach-o :)

**Closed** 2017-05-23 08:50 UTC
