### ISSUE TITLE
Cannot share tasks with users

### ISSUE THREAD

**Issue by GregSutcliffe** [owncloud/tasks#326] opened 2016-07-14 16:51 UTC
This might just be me - the README claims you can share tasks with users, but I can't find it...
### Steps to reproduce
1. Create two users
2. Enable Tasks
3. Create a task as User A
### Expected behaviour

I should now be able to share this task with the second user.
### Actual behaviour

No share icons can be seen, clicking around doesn't show any share options. Screenshot attached/
![2016-07-14-174635_1261x909_scrot](https://cloud.githubusercontent.com/assets/827786/16847865/f9c47f00-49ea-11e6-9081-45d88cd62dab.png)
### Server configuration

**Operating system**: Raspbian 8.0 (RasPi3)

**Web server:** Apache

**Database:** PostgreSQL

**PHP version:** 5.6.22

**ownCloud version:** 9.0.52

**Tasks version:** 0.9.1

**Updated from an older ownCloud or fresh install:** Fresh install

**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.2.1
  - admin_audit: 1.0.0
  - calendar: 1.2.2
  - comments: 0.2
  - contacts: 1.3.1.0
  - dav: 0.1.6
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_external: 0.5.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - news: 8.8.0
  - notifications: 0.2.3
  - password_policy: 1.0.0
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - tasks: 0.9.1
  - templateeditor: 0.1
  - theming: 0.1.0
  - updatenotification: 0.1.0
Disabled:
  - encryption
  - external
  - galleryplus
  - user_external
  - user_ldap
  - user_saml
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "ocuba8ah9rsi",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "prism.elysium.emeraldreverie.org"
        ],
        "datadirectory": "\/var\/www\/nextcloud\/data",
        "overwrite.cli.url": "https:\/\/prism.elysium.emeraldreverie.org\/nextcloud",
        "dbtype": "pgsql",
        "version": "9.0.52.0",
        "dbname": "nextcloud",
        "dbhost": "127.0.0.1",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "installed": true,
        "mail_from_address": "nextcloud",
        "mail_smtpmode": "php",
        "mail_domain": "emeraldreverie.org"
    },
    "apps": {
        "activity": {
            "installed_version": "2.2.1",
            "types": "filesystem",
            "enabled": "yes"
        },
        "admin_audit": {
            "installed_version": "1.0.0",
            "types": "logging",
            "enabled": "yes"
        },
        "backgroundjob": {
            "lastjob": "6"
        },
        "calendar": {
            "installed_version": "1.2.2",
            "types": "",
            "enabled": "yes",
            "ocsid": "168707"
        },
        "comments": {
            "installed_version": "0.2",
            "types": "logging",
            "enabled": "yes"
        },
        "contacts": {
            "installed_version": "1.3.1.0",
            "types": "",
            "enabled": "yes",
            "ocsid": "168708"
        },
        "core": {
            "installedat": "1468195168.0798",
            "public_files": "files_sharing\/public.php",
            "remote_files": "dav\/appinfo\/v1\/webdav.php",
            "remote_webdav": "dav\/appinfo\/v1\/webdav.php",
            "remote_dav": "dav\/appinfo\/v2\/remote.php",
            "remote_contacts": "dav\/appinfo\/v1\/carddav.php",
            "remote_carddav": "dav\/appinfo\/v1\/carddav.php",
            "remote_calendar": "dav\/appinfo\/v1\/caldav.php",
            "remote_caldav": "dav\/appinfo\/v1\/caldav.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "oc.integritycheck.checker": "[]",
            "lastupdateResult": "[]",
            "shareapi_allow_mail_notification": "no",
            "shareapi_allow_public_notification": "yes",
            "lastcron": "1468513769",
            "lastupdatedat": "1468512762"
        },
        "dav": {
            "installed_version": "0.1.6",
            "types": "filesystem",
            "enabled": "yes"
        },
        "external": {
            "sites": "[[\"Tracks\",\"https:\\\/\\\/tracks.emeraldreverie.org\",\"external.svg\"]]",
            "enabled": "no",
            "installed_version": "1.2",
            "ocsid": "166046",
            "types": ""
        },
        "federatedfilesharing": {
            "installed_version": "0.1.0",
            "types": "",
            "enabled": "yes"
        },
        "federation": {
            "installed_version": "0.0.4",
            "types": "authentication",
            "enabled": "yes"
        },
        "files": {
            "installed_version": "1.4.4",
            "types": "filesystem",
            "enabled": "yes",
            "cronjob_scan_files": "500"
        },
        "files_external": {
            "installed_version": "0.5.2",
            "ocsid": "166048",
            "types": "filesystem",
            "enabled": "yes"
        },
        "files_pdfviewer": {
            "installed_version": "0.8.1",
            "ocsid": "166049",
            "types": "",
            "enabled": "yes"
        },
        "files_sharing": {
            "installed_version": "0.9.1",
            "types": "filesystem",
            "enabled": "yes"
        },
        "files_texteditor": {
            "installed_version": "2.1",
            "ocsid": "166051",
            "types": "",
            "enabled": "yes"
        },
        "files_trashbin": {
            "installed_version": "0.8.0",
            "types": "filesystem",
            "enabled": "yes"
        },
        "files_versions": {
            "installed_version": "1.2.0",
            "types": "filesystem",
            "enabled": "yes"
        },
        "files_videoplayer": {
            "installed_version": "0.9.8",
            "types": "",
            "enabled": "yes"
        },
        "firstrunwizard": {
            "installed_version": "1.1",
            "ocsid": "166055",
            "types": "",
            "enabled": "yes"
        },
        "gallery": {
            "installed_version": "14.5.0",
            "types": "",
            "enabled": "yes"
        },
        "galleryplus": {
            "enabled": "no",
            "installed_version": "15.1.0",
            "types": "",
            "ocsid": "169116"
        },
        "news": {
            "installed_version": "8.8.0",
            "types": "",
            "enabled": "yes",
            "ocsid": "168040"
        },
        "notifications": {
            "installed_version": "0.2.3",
            "types": "logging",
            "enabled": "yes"
        },
        "password_policy": {
            "installed_version": "1.0.0",
            "types": "",
            "enabled": "yes"
        },
        "provisioning_api": {
            "installed_version": "0.4.1",
            "types": "prevent_group_restriction",
            "enabled": "yes"
        },
        "systemtags": {
            "installed_version": "0.2",
            "types": "logging",
            "enabled": "yes"
        },
        "tasks": {
            "installed_version": "0.9.1",
            "ocsid": "164356",
            "types": "",
            "enabled": "yes"
        },
        "templateeditor": {
            "installed_version": "0.1",
            "types": "",
            "enabled": "yes"
        },
        "theming": {
            "installed_version": "0.1.0",
            "types": "",
            "enabled": "yes",
            "cachebuster": "2"
        },
        "updatenotification": {
            "installed_version": "0.1.0",
            "types": "",
            "enabled": "yes"
        }
    }
}
```

**Are you using external storage, if yes which one:** local (mounted NFS)

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no
### Client configuration

**Browser:** Firefox 46.0.1

**Operating system:** ArchLinux

**CalDAV-clients:** None, browser only

**Comment by raimund-schluessler** [comment] 2016-07-15 07:08
No, you don't miss anything. Sharing tasks from within the Tasks app is not possible atm. The only workaround I can give you is creating a calendar/list from within the Calendar app and share the whole calendar with the other user. That way he can see all tasks within this list. Sharing single tasks is not possible at all at the moment. This has to be implemented yet.

The readme is from the old Tasks app for oC < 9 where Calendar app and Tasks app where closely bundled and should be updated.

**Comment by olantrust** [comment] 2016-07-19 10:17
@raimund-schluessler  Would this issue cover sharing a task list to another user (from within the Tasks app)? Or should we create another issue for that feature?

**Comment by Quix0r** [comment] 2016-08-30 19:11
Please consider making it possible to share tasks/task lists with other users. E.g. sharing your tasks with work-mates might be a helpful think. Here is what I (for nextcloud, but still this app is not migrated) wrote: https://social.mxchange.org/notice/532689

**Comment by ccoenen** [comment] 2016-09-25 08:49
This is a duplicate of #6 but i think this one has more meaningful (and up to date) information. Voting to close that other ticket.

**Comment by ccoenen** [comment] 2016-09-25 08:52
Another duplicate: #47

**Comment by vollknorke1337** [comment] 2019-04-24 22:42
Any updates here and on #408?

**Comment by cma1kep** [comment] 2019-05-22 21:24
Nice feature for small/big company for sharing task between users.
Now we are using alternatives like wunderlist. 
Hope to see it in owncloud.

**Comment by dlandon** [comment] 2020-03-14 11:03
This isn't anything I will be implementing. I do not have the time to commit to learning ownCloud enough to work on this app with no compensation for my time. I would suggest you use a client that supports the functionality you want and let ownCloud be the repository for your tasks..

**Closed by dlandon** 2020-03-14 11:03 UTC
Labels: enhancement

**Comment by Quix0r** [comment] 2020-04-04 23:14
That is what you get with FLOSS projects, no money-compensation but respect earned from the community for good work. If that is what you don't want, don't contribute to FLOSS projects.

**Comment by ccoenen** [comment] 2020-04-04 23:33
Yes, respect, _and_ bullshit comments.

**Comment by dlandon** [comment] 2020-04-13 12:02
I took over this project to get it back on the Marketplace so users did not have to manually install it.  I didn't intend to take on another development project.  I have way too many right now that I am struggling to keep up with, earning more respect than I can handle.
 
Your badgering me to work on this project is not inspiring and is rather annoting.

Feel free to do a PR and earn yourself a lot of respect.
